export const NOTIFICATION_TYPES = {
  MATERIAL_NEW: 'MATERIAL_NEW',
  DEADLINE_REMINDER: 'DEADLINE_REMINDER',
  ANSWER_ACCEPTED: 'ANSWER_ACCEPTED',
  NEW_ANSWER: 'NEW_ANSWER',
  FRIEND_REQUEST: 'FRIEND_REQUEST',
  FRIEND_ACTIVITY: 'FRIEND_ACTIVITY',
  REVIEW_HELPFUL: 'REVIEW_HELPFUL',
  GROUP_INVITE: 'GROUP_INVITE',
  EVENT_REMINDER: 'EVENT_REMINDER',
} as const

export type NotificationType =
  (typeof NOTIFICATION_TYPES)[keyof typeof NOTIFICATION_TYPES]
